# Generated by Django 5.0.1 on 2024-01-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='times_used',
        ),
        migrations.AddField(
            model_name='recipeproduct',
            name='times_cooked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recipeproduct',
            name='weight',
            field=models.FloatField(),
        ),
    ]
