# Generated by Django 5.0.1 on 2024-01-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_alter_recipeproduct_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeproduct',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='products',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='recipeproduct',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
